[openai]
model = "gpt-3.5-turbo"
temperature = 0.3
top_p = 1
max_tokens = 2048

[audio]
input_device = 4 # the device for voice input (list devices with "lm")
input_timeout = 5 # the number of seconds after which listening stops and transcriptions starts
input_limit = 20 # the maximum number of seconds that can be listened to in one go

[voices]
english = "en-GB-Neural2-B"
french = "fr-FR-Neural2-C"
german = "de-DE-Neural2-B"
spanish = "es-ES-Neural2-B"
russian = "ru-RU-Wavenet-B"

[conversations]
data_folder = "./"

[modes]
normal = ""
table = "Be very precise and concise, display only a table with values separated by | about this topic : "
code = "I want you to act as a # developer. Output # for any requests and only #, nothing else. Add comments inside the # code. Write only # code that does the following : "
trans = "Translate this into # : "
char = "Imagine you are writing a novel about #. I want you to respond and answer like # using the tone, manner and vocabulary # would use. Do not write any explanations. Only answer like #. You must know all of the knowledge of #. My first question is : "
sum = "Summarize this and display it in a list of bullet points : "
csv = "Print a CSV list of : "

[theme]
section = "#d3869b" # pink
info = "#8ec07c" # aqua
success = "#b8bb26" # green
warning = "#fabd2f" # yellow
error = "#fb4934" # red
prompt = "#928374" # grey
answer = "#83a598" # blue
